        SUBROUTINE EDDCMP(MMAT,EMAT,EVAL1,EVAL2,N,IV1,FV1,IERR)
        INTEGER N,IS1,IS2,IV1(N),IERR
        DOUBLE PRECISION MMAT(N,N),EMAT(N,N),EVAL1(N),EVAL2(N),FV1(N)

        CALL BALANC(N,N,MMAT,IS1,IS2,FV1)
        CALL ELMHES(N,N,IS1,IS2,MMAT,IV1)
        CALL ELTRAN(N,N,IS1,IS2,MMAT,IV1,EMAT)
        CALL HQR2(N,N,IS1,IS2,MMAT,EVAL1,EVAL2,EMAT,IERR)
        CALL BALBAK(N,N,IS1,IS2,FV1,N,EMAT)
       RETURN
       END
